### PR TITLE
changed to li, a tag

### PR DESCRIPTION
**Pull request by jakekwak**
if add `headingID`, I think we have to use this one into link.

### CODE REVIEW

**Comment by jakekwak** [comment]
I will close this

**Comment by Vanessa219** [comment]
I'm so sorry, I haven't had time to deal with it recently.

**Comment by jakekwak** [comment]
I will let you know when I get better.  I am waiting the solution of new SV mode (especially nested block)

**Comment by Vanessa219** [comment]
maybe you can use ir or wysiwyg mode first.

**Comment by jakekwak** [comment]
Personally,  I made the old style sv mode.(sv2 mode)

**Comment by Vanessa219** [comment]
Believe that our sv mode is better than before, but it needs more improvements.

**Comment by jakekwak** [comment]
I know. Everything looks good, except for the nested blocks.

**Comment by Vanessa219** [comment]
OK, we will do our best.

**Pull request closed without merging**
